version: '3.9'

services:
  pgdb:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: pnpm run start:dev api
    env_file:
      - .env
    ports:
      - '5790:5790'
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgdb
      - redis

  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: pnpm run start:dev payment
    env_file:
      - .env
    ports:
      - '5791:5791'
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgdb
      - redis

volumes:
  redis:
    driver: local
  pg_volume:
