// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: proto/payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

// export const protobufPackage = 'payment';

export interface CreateCustomerMessage {
  id: string;
  email: string;
}

export interface CreateCustomerResponse {
  customerId: string;
}

export interface CreateChargeMessage {}

export interface CreateChargeResponse {}

export const PAYMENT_PACKAGE_NAME = 'payment';

export interface PaymentServiceClient {
  createCustomer(
    request: CreateCustomerMessage,
  ): Observable<CreateCustomerResponse>;

  createCharge(request: CreateChargeMessage): Observable<CreateChargeResponse>;
}

export interface PaymentServiceController {
  createCustomer(
    request: CreateCustomerMessage,
  ):
    | Promise<CreateCustomerResponse>
    | Observable<CreateCustomerResponse>
    | CreateCustomerResponse;

  createCharge(
    request: CreateChargeMessage,
  ):
    | Promise<CreateChargeResponse>
    | Observable<CreateChargeResponse>
    | CreateChargeResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createCustomer', 'createCharge'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('PaymentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('PaymentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PAYMENT_SERVICE_NAME = 'PaymentService';
